language: node_js
node_js:
  - "node"

cache:
directories:
  - node_modules

install:
  - npm install gitbook-cli -g
  - gitbook install

before_script:

script:
  - gitbook build

after_script:
  - cd ./_book
  - git init
  - git config user.name "${USER_NAME}"
  - git config user.email "${USER_EMAIL}"
  - git add .
  - git commit -m "Update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages

branches:
  only:
    - master